name: atac
channels:
  - conda-forge
  - bioconda
dependencies:
  - sra-tools
  - libxcrypt
  - trim-galore
  - python=3.7.16
  - meme
  - samtools
  - bowtie2
  - picard
  - pygenometracks
  - deeptools
  - macs2
  - seaborn
  - scipy
  - matplotlib
  - numpy
  - bedtools
  - pandas
